name: Build, Push Docker Image
on:
  push:
    branches: [ "master" ]
env: 
  IMAGE_NAME: tech4mud/udit-ridecell-image
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and push Docker image
      run: | 
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u tech4mud --password-stdin
        docker image build -t "${{ env.IMAGE_NAME }}":"${{ github.GITHUB_SHA }}" .
        docker push "${{ env.IMAGE_NAME }}":"${{ github.GITHUB_SHA }}"
      






      #       - gcloud auth activate-service-account --key-file ${GCP_SA_KEY}
      # - gcloud config set project eyekloud
      # - gcloud config set compute/zone europe-west4-a
      # - gcloud container clusters get-credentials eyekloud-prod-cluster --region europe-west4 --project eyekloud
      # - kubectl set image deployment/${DEPLOYMENT_NAME_PROD} eyekloud-frontend=${CONTAINER_IMAGE_PROD} -n ${NAMESPACE_PROD}

